
# SEO settings
title_prefix: "/"
title: "Android"
title2: "Reverser" # default: ""
description: "Сообщество любителей изучать Android приложения изнутри."
keywords: "android, reverse engineering, practical reverse engineering, reverse engineering уроки, security, apktool, jd-gui, procyon, dalvik, smali, backsmali, apk, byte code, java"
url: https://android-reverser.ru
enforce_ssl: android-reverser.ru
baseurl: null

google_analytics: UA-83539137-1
repo: https://github.com/android-reverser/android-reverser.github.io
disqus_shortname: "android-reverser"
twitter_username: "AndroidReverser"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

author:
  name: "AndroidReverser"

# social settings
og_locale: "ru_RU"
twitter_card: "summary_large_image"
twitter_site: "@AndroidReverser"

gems:
  - bourbon
  - jekyll-paginate

# collections
collections:
  articles:
    output: true
  books:
    output: true

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
